backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "portfolio"
    label: "الأعمال"
    folder: "content/portfolio"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - { label: "الوصف", name: "description", widget: "text" }
      - { label: "الصورة", name: "image", widget: "image" }
