backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "/images"

collections:
  - name: "works"
    label: "الأعمال"
    folder: "content/works"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "العنوان", name: "title", widget: "string" }
      - {label: "المحتوى", name: "body", widget: "markdown"}
      - { label: "الوصف", name: "description", widget: "text" }
      - { label: "الصورة", name: "image", widget: "image" }
      - { label: "التاريخ", name: "date", widget: "datetime" }
